language: python
python:
  - 2.7
install:
  - python bootstrap.py --version 1.7.1
  - bin/buildout -q
script:
  - bin/test
  - bin/vvv setup.py
  - bin/vvv src/spinchimp

notifications:
  irc:
    - "irc.freenode.org#niteoweb"
  email:
    - maintenance@niteoweb.com
